### ISSUE TITLE
Welcome to the club

### ISSUE THREAD

**Issue by jstedfast** [bacome/imapclient#20]
Hi and welcome to the club of IMAP client libraries for .NET ;-)

**Comment by bacome** [comment]
Thank you :)

**Comment by jstedfast** [comment]
Not sure if it's helpful, but if are in need of a MIME parser, you could use [MimeKit](https://github.com/jstedfast/MimeKit) so that you can focus on IMAP.

Another option is to just deal with streams. Another guy I know was working on a really nice IMAP library that supported command pipelining and was fully async (sadly using the Begin/End convention rather than async/await) who was just going the Stream route so that consumers could use any MIME parser they wanted.

I will note that my MimeKit library can convert System.Net.Mail.MailMessage into MimeMessage, but can not go in the other direction. That may be a downside if you want to pair your library with System.Net.Mail for SMTP support. That said, however, System.Net.Mail isn't all that great anyway and implementing SMTP support is trivial if you can do IMAP :)

Anyway... just some random thoughts.

Oh, and I like your class for UIDs - it's very similar to my [UniqueId](https://github.com/jstedfast/MailKit/blob/master/MailKit/UniqueId.cs) design ;-)

**Comment by bacome** [comment]
Thanks for the feedback.
This project was meant to be a fill in while I was running down some other work, but it seems to have taken on a life of its own. I'm definitely not planning on implementing SMTP myself, but I think that some SMTP integration is required to support some possible use cases that I can imagine (e.g. the automatic preparation of an email that a user has to edit or ok-to-send).
The library offers a stream with the whole message in it via the cMessage.Fetch(cSection ...) API (if you pass cSection.All as the section), so if someone wanted to hook up to an external mime parser or SMTP service then they could (and this will probably be required for the sending of sophisticated messages as the conversion to System.Net.Mail.MailMessage that I was planning was going to be very simple and will most likely be an incomplete one - when the time comes I'll include pointers to your project in the documentation if you approve).
The append APIs will definitely take a stream as one of the possible message data sources; I've already spent a bit of time including support for it in the command pipeline.
:)

**Comment by jstedfast** [comment]
> This project was meant to be a fill in while I was running down some other work, but it seems to have taken on a life of its own.

Haha, this is exactly the same for my own IMAP, POP3, SMTP library ([MailKit](https://github.com/jstedfast/MailKit)). :)

I was, at the time, hoping that one of the many other IMAP libraries would pick up [MimeKit](https://github.com/jstedfast/MimeKit), but in the meantime I just wanted to verify that MimeKit had all of the bells and whistles to make it easy to use when writing SMTP, POP3, and IMAP clients.

Anyway, feel free to check out my MailKit library as well - I think you'll find some great design ideas that may help you, or at least might spark some spin-off clever ideas of your own.

The one thing I've still got to figure out is how to allow pipelining of commands.

Have you been able to solve that with your library? I've only skimmed over your source code so far but haven't had the chance to really play with it yet as I was busy rewriting my own library to be fully async.

One thought I had was to have my command-pipeline running in its own thread so that the higher-level public API would just queue commands on the engine which could peek-ahead in the command queue to see which commands could be pipelined (according to the rules in rfc3501), flush them, then read the tagged and untagged responses as they came in, emitting "completed" events (or mark the async Task as completed) so that the public API would know the command was finished and could return to the caller.

**Comment by bacome** [comment]
Pipelining: yes it works.
I solved it with an all async task approach with ‘locking’ to block the submitting of incompatible commands. 
After doing some reading I ruled out using dedicated threads, as the command submitter and response receiver jobs spend most of their time waiting, which, according to my understanding, implies the use of tasks.
The locking approach is required for some commands, as you can’t even prepare the text of a command that includes MSNs if a command that allows EXPUNGEs to arrive is running at the time. The downside of the approach I took is that operations aren’t necessarily executed in the order that they are submitted to the library; e.g. a long run of compatible operations could hold up an incompatible one that was submitted in the middle. I’m not sure how likely that is to cause a problem in the real world however.
For examples of the pipelining in action: the library normally pipelines the NAMESPACE and ID commands at connect time, and if you don't have (or turn off) LIST-STATUS but ask for status information when doing a mailbox listing, it will pipeline all the STATUS commands. Those are both examples where the library is doing the pipelining internally, but it isn’t cheating – it submits the commands internally the same way as they would be from outside. There are tests in the testharness that make sure that the pipelining is working – the two I just found are ZTestSearch3 (which runs SEARCH and SORT at the same time and demonstrates the out of order execution issue) and ZTestPipelineCancellation (primarily a test that cancellation of a submitted command stops it being sent, but it runs two extended SEARCHes at the same time).
Doing the command pipelining was very frustrating and only occasionally satisfying (i.e. it was fun). Good luck!

**Comment by jstedfast** [comment]
I'll have to check out how you did it, thanks!
